import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Link } from "wouter";
import { Database, FileCheck2, ShieldCheck } from "lucide-react";

export default function ManagementPortal() {
  const { user, loading } = useAuth();
  if (loading) return <main className="min-h-screen grid place-items-center bg-[#f4efe5] text-[#123c52]">جارٍ التحقق من الدخول…</main>;
  if (!user) return <main dir="rtl" className="min-h-screen grid place-items-center bg-[#f4efe5] p-6 text-[#123c52]"><section className="max-w-xl border border-[#d7c9b5] bg-white/80 p-8 text-center"><ShieldCheck className="mx-auto text-[#b86f3c]" size={42} /><h1 className="mt-4 text-3xl font-black">المسار الداخلي للأطلس</h1><p className="mt-3 text-slate-600">هذا المسار مخصص لمسؤول النظام وفريق التوثيق والمراجعين. سجّل الدخول بالحساب المؤسسي للمتابعة.</p><Button className="mt-5 bg-[#123c52]" onClick={startLogin}>دخول الإدارة الداخلية</Button><Link href="/public"><Button className="mt-5 mr-2" variant="outline">العودة للمسار العام</Button></Link></section></main>;
  return <main dir="rtl" className="min-h-screen bg-[#f4efe5] p-6 text-[#123c52] md:p-10"><section className="mx-auto max-w-5xl"><header className="border-b border-[#d7c9b5] pb-6"><span className="text-xs font-bold tracking-[0.2em] text-[#b86f3c]">TIDC · INTERNAL WORKSPACE</span><h1 className="mt-2 text-4xl font-black">المسار الداخلي للأطلس</h1><p className="mt-2 text-slate-600">مسؤول النظام · فريق التوثيق · المراجعة والاستيراد.</p></header><div className="mt-8 grid gap-5 md:grid-cols-3"><Link href="/system-admin"><section className="h-full border border-[#d7c9b5] bg-white/80 p-6"><ShieldCheck className="text-[#b86f3c]" /><h2 className="mt-4 text-xl font-bold">مسؤول النظام</h2><p className="mt-2 text-sm text-slate-600">إدارة المستخدمين والصلاحيات والنسخ الاحتياطية.</p></section></Link><Link href="/documentation-team"><section className="h-full border border-[#d7c9b5] bg-white/80 p-6"><FileCheck2 className="text-[#287a70]" /><h2 className="mt-4 text-xl font-bold">فريق التوثيق والمراجعة</h2><p className="mt-2 text-sm text-slate-600">إضافة النقاط، مراجعة الصور، واستيراد KML وExcel.</p></section></Link><Link href="/public"><section className="h-full border border-[#d7c9b5] bg-white/80 p-6"><Database className="text-[#3e7183]" /><h2 className="mt-4 text-xl font-bold">المسار العام</h2><p className="mt-2 text-sm text-slate-600">فتح نسخة الزوار والسواح من الأطلس.</p></section></Link></div><p className="mt-8 text-sm text-slate-500">الحساب الحالي: {user.name || user.email || "الحساب المؤسسي"}</p></section></main>;
}
