export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
<<<<<<< HEAD
=======
  appBaseUrl: process.env.APP_BASE_URL ?? "http://localhost:3000",
  authMode: process.env.AUTH_MODE ?? "local",
  storageDriver: process.env.STORAGE_DRIVER ?? "local",
  storageDir: process.env.STORAGE_DIR ?? "./storage/uploads",
  publicStorageUrl: process.env.PUBLIC_STORAGE_URL ?? "/uploads",
  s3Endpoint: process.env.S3_ENDPOINT ?? "",
  s3Region: process.env.S3_REGION ?? "us-east-1",
  s3Bucket: process.env.S3_BUCKET ?? "",
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
  s3PublicBaseUrl: process.env.S3_PUBLIC_BASE_URL ?? "",
  aiApiUrl: process.env.AI_API_URL ?? "",
  aiApiKey: process.env.AI_API_KEY ?? "",
  aiModel: process.env.AI_MODEL ?? "",
  notificationWebhookUrl: process.env.NOTIFICATION_WEBHOOK_URL ?? "",
  mapsApiUrl: process.env.MAPS_API_URL ?? "",
  mapsApiKey: process.env.MAPS_API_KEY ?? "",
  transcriptionApiUrl: process.env.TRANSCRIPTION_API_URL ?? "",
  transcriptionApiKey: process.env.TRANSCRIPTION_API_KEY ?? "",
>>>>>>> origin/repair/latest-atlas-2026
};
